spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "cards-4.0"

cards:
  message: "Welcome to EazyBank accounts related local APIs "
  contactDetails:
    name: "John Prod - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345