spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "loans-5.0"

loans:
 message: "Welcome to EazyBank accounts related local APIs "
 contactDetails:
  name: "John qa - Developer"
  email: "john@eazybank.com"
 onCallSupport:
  - (555) 555-1234
  - (555) 523-1345