build:
  version: "Cards-3.0"

cards:
  message: "Welcome to EazyBank accounts related local APIs "
  contactDetails:
    name: "John Default - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
